# Generated by Django 4.1.3 on 2022-12-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('EventName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('EventDate', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
                ('Alt_Phone_number', models.CharField(max_length=12)),
                ('Effordable_Amount', models.FloatField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
